#------------------------------------------
#            Virtual Shop Config
#------------------------------------------

#
# Database Configuration
#

MySQL:
  port:             3306
  username:         ChatShop
  host:             localhost
  password:         password
  database:         ChatShop

#
# Market Policy
#

global-max-price:   10000000

#
# Gamemode Configuration
#

# Only players in these gamemodes can buy, sell, etc.
allowed-modes:
  - SURVIVAL
# Whether players in the wrong gamemode can query the
# shop (/find, /sales, etc.)
query-anyone:       true

#
# Chat Confiuration
#

chat:
  broadcast-offers: true
  page-length:      10
  prefix: 
    color:          DARK_PURPLE
    tag:            '[OShop]'
  colors:
    date:           DARK_GRAY
    error:          DARK_RED
    helpUsage:      GRAY
    item:           YELLOW
    player:         YELLOW
    price:          YELLOW
    quantity:       RED
    text:           BLUE