author: ObsidianCraft Staff
authors: [Wesley27, LazrCowboy, SirNius]
description: Allows players to buy and sell goods via chat.
main: com.niusworks.chatshop.ChatShop
name: ChatShop
version: 1.0.0
depend: [Vault]
commands:
    buy:
        description: Buy goods for sale on the Chat Shop.
        usage: /buy <amount> <item> [maxprice]
    cancel:
        description: Remove items from your existing listing on the Chat Shop.
        usage: /cancel <amount> <item>
    chatshop:
        description: Get a list of Chat Shop commands.
        usage: /chatshop [page]
        aliases: [chatshop,vm,vs,cs,os,oshop,shop]
    confirm:
        description: Confirm a pending transaction or toggle confirmations.
        usage: /confirm [toggle <buy|sell>]
    dump:
        description: Dump your inventory to the Chat Shop.
        usage: /dump
    find:
        description: Find offers for an item.
        usage: /price <item> [page]
    history:
        description: Show a history of Chat Shop transactions.
        usage: /history [player] [page]
        aliases: [sales]
    quote:
        description: Get a quote for the given items.
        usage: /quote <quantity> <item>
    reprice:
        description: Change the price of something you have on the Chat Shop.
        usage: /reprice <item> <newPrice>
    sell:
        description: Put goods up for sale on the Chat Shop.
        usage: /sell <amount> <item | "hand"> <price | "-">
    stock:
        description: List all items available from a user on the Chat Shop.
        usage: /stock [player] [page]
permissions:
    chatshop.admin:
        description: Access to administrative commands and overrides.
        default: OP
    chatshop.buy:
        description: Allow usage of /buy
        default: true
    chatshop.cancel:
        description: Allow usage of /cancel
        default: true
    chatshop.confirm:
        description: Allow usage of /confirm
        default: true
    chatshop.dump:
        description: Allow usage of /dump
        default: true
    chatshop.find:
        description: Allow usage of /find
        default: true
    chatshop.help:
        description: Allow usage of /chatshop
        default: true
    chatshop.history:
        description: Allow usage of /history
        default: true
    chatshop.history.other:
        description: Allow querying history of other players
        default: OP
    chatshop.reprice:
        description: Allow usage of /reprice
        default: true
    chatshop.sell:
        description: Allow usage of /sell
        default: true
    chatshop.stock:
        description: Allow usage of /stock
        default: true
