#
#   -- ChatShop Config --
#
#   Configuration for the ChatShop plugin for ObsidianCraft Network,
#   by ObsidianCraft staff.
#


##########################
# Database Configuration #
##########################

MySQL:
  port:             3306
  username:         ChatShop
  host:             localhost
  password:         password
  database:         ChatShop

# Time in milliseconds between keep-alive queries.
# MySQL's default timeout for (inactive) database connections is 8 hours
# (28,800,000 ms). ChatShop can quietly send a query to the database
# periodically to keep the connection alive, so that quieter servers can
# use the ChatShop continuously without having to reconfigure MySQL.
# A value less than 60,000 will disable the feature altogether.
  keep-alive:         14400000

#################
# Market Policy #
#################

# Global maximum price for all items.
# items.csv does NOT override this.
global-max-price:   10000000

# Time in milliseconds a user has in which to /confirm.
confirm-timeout:    10000

####################################
# Gamemode and World Configuration #
####################################

# Only players in these gamemodes can buy, sell, etc.
allowed-modes:
  - SURVIVAL
  
# Only players in these worlds can buy, sell, etc.
allowed-worlds:
  - Survival
  - Survival_the_end
  - Survival_nether

# Whether players in the wrong gamemode or world can query the
# shop (/find, /sales, etc.)
query-anyone:       true

#####################
# Chat Confiuration #
#####################

# Chat colors must be human-readable names
# found in Bukkit's ChatColor enum.

chat:
  broadcast-offers: true
  page-length:      10
  prefix: 
    color:          DARK_PURPLE
    tag:            '[OShop]'
  colors:
    date:           DARK_GRAY
    error:          DARK_RED
    helpUsage:      GRAY
    item:           AQUA
    player:         LIGHT_PURPLE
    price:          YELLOW
    quantity:       RED
    text:           BLUE