author: ObsidianCraft Staff
authors: [Wesley27, LazrCowboy, SirNius]
description: Allows players to buy and sell goods via chat.
main: com.niusworks.chatshop.ChatShop
name: ChatShop
version: 1.0.8
depend: [Vault]
commands:
    buy:
        description: |-
          Buy a quantity of the cheapest of the specified item from the market.
          You can use "hand" to refer to the item currently in your main hand.
          If you specify a maximum price then ChatShop will not allow you to spend
          more than that price on any one unit of the item you're buying.
        usage: /buy <quantity> <item | "hand"> [maxprice]
    cancel:
        description: |-
          Remove some of your own specified items from the market.
          You can say "all" instead of a number to remove the whole stock. 
          You can use "hand" to refer to the item currently in your main hand.
        usage: /cancel <quantity | "all"> <item | "hand">
    chatshop:
        description: Show Chat Shop help and commands.
        usage: /chatshop [page]
        aliases: [chatshop,cs,os,oshop,potion,potions,shop,vm,vs]
    confirm:
        description: "Confirm a pending transaction, or toggle confirmations whether you're using /confirm at all."
        usage: /confirm [toggle <buy|sell>]
    csadmin:
        description: Central command for administrative functions.
        usage: /csadmin <command>
    dump:
        description: |-
          Post your whole inventory to the market.
          Only items for which you already have some on the market will be posted.
          Your prices will not be changed.
        usage: /dump
    find:
        description: |-
          Find an item on the market.
          You can use "hand" to refer to the item currently in your main hand.
        usage: /find <item | "hand"> [page]
        aliases: [f]
    history:
        description: Show a history of Chat Shop transactions.
        usage: /history [player] [page]
        aliases: [sales]
    quote:
        description: |-
          Find out how much it would cost to buy a given quantity of some item.
          You can use "hand" to refer to the item currently in your main hand.
        usage: /quote <quantity> <item | "hand">
    reprice:
        description: |-
          Change the price of something you're already selling.
          You can use "hand" to refer to the item currently in your main hand.
        usage: /reprice <item | "hand"> <newPrice>
    sell:
        description: |-
          Put items up for sale on the ChatShop.
          You can say "all" instead of a number to sell as much as you have in your inventory.
          You can use "hand" to refer to the item currently in your main hand.
          You can use "-" instead of a price to use your current market price, if you have one.
          The price is per item, not for the whole stock.
        usage: /sell <quantity> <item | "hand"> <priceEach | "-">
    stock:
        description: Show everything a player is currently selling on the ChatShop.
        usage: /stock [player] [page]
permissions:
    chatshop.admin:
        description: Access to administrative commands and overrides.
        default: OP
    chatshop.buy:
        description: Allow usage of /buy
        default: true
    chatshop.cancel:
        description: Allow usage of /cancel
        default: true
    chatshop.confirm:
        description: Allow usage of /confirm
        default: true
    chatshop.dump:
        description: Allow usage of /dump
        default: true
    chatshop.find:
        description: Allow usage of /find
        default: true
    chatshop.help:
        description: Allow usage of /chatshop
        default: true
    chatshop.history:
        description: Allow usage of /history
        default: true
    chatshop.history.other:
        description: Allow querying history of other players
        default: OP
    chatshop.quote:
        description: Allow usage of /quote
        default: true
    chatshop.reprice:
        description: Allow usage of /reprice
        default: true
    chatshop.sell:
        description: Allow usage of /sell
        default: true
    chatshop.stock:
        description: Allow usage of /stock
        default: true
